---
- hosts: jenkins_controllers
  remote_user: root
  pre_tasks:
    - name: Install packages
      apt:
        name:
          - curl
          - firewalld
          - openjdk-11-jdk
        update_cache: yes
    - name: Open ports for HTTP and HTTPS
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
        zone: public
      loop:
        - http
        - https
        - jenkins
    - name: Set floating ip
      template:
        src: templates/interfaces.j2
        dest: /etc/network/interfaces
    - name: Reload services
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - firewalld
        - networking
    - name: Configure Jenkins
      template:
        src: templates/jenkins.yaml.j2
        dest: "{{ jenkins_home }}/jenkins.yaml"
  post_tasks:
    - name: Disable setup wizard
      jenkins_script:
        script: |
          import static jenkins.model.Jenkins.instance as jenkins
          import jenkins.install.InstallState
          if (!jenkins.installState.isSetupComplete()) {
            InstallState.INITIAL_SETUP_COMPLETED.initializeState()
          }
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
    - name: Create .ssh folder for Jenkins user
      become: yes
      become_user: jenkins
      file:
        path: "{{ jenkins_home }}/.ssh"
        state: directory
        mode: '700'
        owner: jenkins
    - name: Add agents to known hosts
      become: yes
      become_user: jenkins
      known_hosts:
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan {{ item }}') }}"
      with_items: "{{ groups.jenkins_agents }}"
  vars:
    user_to_create: "{{ jenkins_user }}"
    jenkins_hostname: "{{ hostname }}"
    jenkins_package_state: latest
    jenkins_plugins_state: latest
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
    jenkins_init_changes:
      - option: "JAVA_ARGS"
        value: "{{ jenkins_java_options }}"
    jenkins_admin_username: "{{ admin_username }}"
    jenkins_admin_password: "{{ admin_password }}"
    jenkins_plugins:
      - ssh-slaves
      - git
      - subversion
      - configuration-as-code
    jenkins_plugins_install_dependencies: true
    certbot_create_if_missing: true
    certbot_admin_email: "{{ admin_email }}"
    certbot_certs:
    - domains:
        - "{{ hostname }}"
        - "www.{{ hostname }}"
    nginx_install_from: os_repository
    nginx_vhosts:
    - listen: "443 ssl"
      server_name: "{{ hostname }}"
      extra_parameters: |
        location / {
          include /etc/nginx/proxy_params;
          proxy_pass http://localhost:8080;
          proxy_read_timeout 90s;
          proxy_redirect http://localhost:8080 https://{{ hostname }};
        }
        ssl_certificate /etc/letsencrypt/live/{{ hostname }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ hostname }}/privkey.pem;
  roles:
    - role: create-user
    - role: geerlingguy.nginx
    - role: geerlingguy.certbot
    - role: geerlingguy.jenkins

- hosts: jenkins_agents
  remote_user: "{{ jenkins_user }}"
  post_tasks:
    - name: Generate ssh key for agent
      local_action:
        module: openssh_keypair
        path: "./jenkins_agent"
    - name: Add public key to jenkins agent authorised keys
      authorized_key:
        user: "{{ jenkins_user }}"
        key: "{{ lookup('file', './jenkins_agent.pub') }}"
    - name: Install Java
      become: True
      apt:
        name: openjdk-11-jdk
  vars:
    user_to_create: "{{ jenkins_user }}"
  roles:
    - role: create-user
